allprojects {
    tasks.withType(org.gradle.api.tasks.compile.JavaCompile).configureEach {
        sourceCompatibility = "17"
        targetCompatibility = "17"
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            jvmTarget = "17"
        }
    }
}
